// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <QuartzCore/QuartzCore.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) window;
-(IBAction) storyboard;

@end

@interface CustomTableViewCell: UITableViewCell
-(IBAction) layoutSubviews;
-(IBAction) todo_item;
-(IBAction) render_label;
-(IBAction) tick_label;
-(IBAction) cross_label;
-(IBAction) create_cue_label;
-(IBAction) gradient_layer;
-(IBAction) item_complete_layer;
-(IBAction) colors;
-(IBAction) recognizer;
-(IBAction) handle_pan:(id) recognizer;
-(IBAction) state_began:(id) recognizer;
-(IBAction) state_changed:(id) recognizer;
-(IBAction) state_ended:(id) recognizer;
-(IBAction) gestureRecognizerShouldBegin:(id) gesture_recognizer;
-(IBAction) textFieldShouldReturn:(id) text_field;
-(IBAction) textFieldShouldBeginEditing:(id) text_field;
-(IBAction) textFieldDidBeginEditing:(id) text_field;
-(IBAction) textFieldDidEndEditing:(id) text_field;

@end

@interface MainViewController: UIViewController

@property IBOutlet UITableView * table_view;

-(IBAction) viewDidLoad;
-(IBAction) todo_item_deleted:(id) todo_item;
-(IBAction) todo_item_saved;
-(IBAction) reload_table_view_after_delete;
-(IBAction) todo_item_added;

@end

@interface TodoItem: NSObject
@end

@interface TodoListManager: NSObject
-(IBAction) initialize;
-(IBAction) create_todo_with_content:(id) content;
-(IBAction) storage_file;
-(IBAction) load;
-(IBAction) save;

@end

@interface OpenStruct: BasicObject
-(IBAction) initialize:(id) hash;

@end

@interface StrikeThroughText: UITextField
-(IBAction) initWithFrame:(id) frame;
-(IBAction) layoutSubviews;
-(IBAction) resize_strike_through;
-(IBAction) strikethrough;
-(IBAction) strikethrough_layer;

@end

